#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pyliblzma
Version  : 0.5.3
Release  : 10
URL      : https://pypi.python.org/packages/source/p/pyliblzma/pyliblzma-0.5.3.tar.bz2
Source0  : https://pypi.python.org/packages/source/p/pyliblzma/pyliblzma-0.5.3.tar.bz2
Summary  : Python bindings for liblzma
Group    : Development/Tools
License  : LGPL-3.0+ LGPL-3.0 GPL-3.0
Requires: pyliblzma-python
BuildRequires : python-dev
BuildRequires : setuptools
BuildRequires : xz-dev

%description
PylibLZMA provides a python interface for the liblzma library
to read and write data that has been compressed or can be decompressed
by Lasse Collin's lzma utils.

%package python
Summary: python components for the pyliblzma package.
Group: Default

%description python
python components for the pyliblzma package.


%prep
%setup -q -n pyliblzma-0.5.3

%build
%{__python} setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
%{__python} setup.py test
%install
rm -rf %{buildroot}
%{__python} setup.py install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
